plot_spider_pose([
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
        0,
        -pi / 8,
        -pi / 8,
    ])